Dz 04
chicony83/MyHomeWorks pull request #4
Opened 2020-09-30 12:14 UTC by chicony83

2020-09-30 13:43 UTC, Nazarov-AA approved these changes

2020-09-30 14:27 UTC, stasenkots requested changes
You should use ViewModel in the task.And coroutines for emulating "receiving some data from server".also better to group repeated logic

2020-10-01 18:53 UTC, stasenkots commented on app/src/main/java/com/example/myhomeworks/IncomingData.kt
> +    var company1_potato = MutableLiveData(0)
Repeated logic.You can keep vegitables in some class.

2020-10-14 08:54 UTC, AliaksandrG approved these changes

2020-11-18 12:46 UTC, merged